services:
  - type: web
    name: wvms
    env: python
    region: singapore  # Choose the region closest to your users
    buildCommand: "./build.sh"  # This will install dependencies and initialize the database
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: app.py
    autoDeploy: true
    healthCheckPath: /login
    plan: free
