services:
  - type: web
    name: wvms
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
    plan: free
